# TODO create dockerfiles
version: "3"


services:
  #eurika:
  #  container_name: "eurika_server"
  #  build:
  #    dockerfile: eurika-server/Dockerfile
  #  restart: unless-stopped
    #ports:
    #  - "8080:80"
  keycloak:
    container_name: keycloak
    hostname: keycloak
    image: quay.io/keycloak/keycloak:latest
    command: ["start-dev", "--import-realm"]
    ports:
      - "3212:8080"
    volumes:
      - ./realms:/opt/keycloak/data/import
    environment:
      KC_DB: ${DB_NAME}
      KC_DB_URL: ${DB_URL}
      KC_DB_USERNAME: ${DB_USERNAME}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KC_DB_SCHEMA: ${DB_SCHEMA}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: true

  db:
    container_name: pg_container
    image: postgres
    restart: always
    hostname: database
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    ports:
      - "88:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: test