# TODO create dockerfiles
version: "3"


services:
  #eurika:
  #  container_name: "eurika_server"
  #  build:
  #    dockerfile: eurika-server/Dockerfile
  #  restart: unless-stopped
    #ports:
    #  - "8080:80"
  keycloak:
    container_name: keycloak
    hostname: keycloak
    image: quay.io/keycloak/keycloak:latest
    command: ["start-dev", "--import-realm"]
    ports:
      - "8080:8080"
    volumes:
      - ./realms:/opt/keycloack/data/import
    environment:
      KC_DB: ${DB_NAME}
      KC_DB_URL: ${DB_URL}
      KC_DB_USERNAME: ${DB_USERNAME}
      KC_DB_PASSWORD: ${DB_PASSWORD}
      KC_DB_SCHEMA: ${DB_SCHEMA}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
     